CREATE TABLE problem (
  problem_id BIGINT NOT NULL IDENTITY,
  problem_name VARCHAR(500) UNIQUE NOT NULL,
  program_id BIGINT NOT NULL,
  comment VARCHAR(10000) DEFAULT '' NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY(program_id) REFERENCES program(program_id)
);