CREATE TABLE program (
  program_id BIGINT NOT NULL IDENTITY,
  program_name VARCHAR(500) UNIQUE NOT NULL,
  description VARCHAR(10000) NOT NULL,
  hint VARCHAR(1000) NOT NULL,
  code VARCHAR(65000) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);