package com.github.funczz.ruby_calc.core.model.setting

enum class SettingItems {
    PROBLEM_INDEX_VALUE,
    PROBLEM_INDEX_COLUMN,
    PROBLEM_INDEX_ORDER_BY,
    PROBLEM_INDEX_LIMIT,
    PROBLEM_DETAILS_ID,
    PROGRAM_INDEX_VALUE,
    PROGRAM_INDEX_COLUMN,
    PROGRAM_INDEX_ORDER_BY,
    PROGRAM_INDEX_LIMIT,
    PROGRAM_DETAILS_ID,
    PROGRAM_EDIT_ID,
    PROGRAM_EDIT_NAME,
    PROGRAM_EDIT_DESCRIPTION,
    PROGRAM_EDIT_HINT,
    PROGRAM_EDIT_CODE,
}
